document.write("<div id=\"logo\">");
document.write("<div id=\"logo_text\">");
document.write("<!-- class=\"logo_colour\", allows you to change the colour of the text -->");
document.write("<h1><a href=\"index.html\">Lipeng Liu<span class=\"logo_colour\">（刘利朋）</span></a></h1>");
document.write("<h2>我能故我在</h2>");
document.write("</div>");
document.write("<div id=\"logo_badgeCASIIE\" class=\"logo_badge\">");
document.write("<a href=\"http://cvpr.ouc.edu.cn\" target=\"_blank\"><img src=\"Images/vision.png\" title=\"中国海洋大学视觉实验室\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeHUST\" class=\"logo_badge\">");
document.write("<a href=\"http://it.ouc.edu.cn/Display/Index.aspx\" target=\"_blank\"><img src=\"Images/xinxi.png\" title=\"中国海洋大学信息学院\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeYNU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.ouc.edu.cn\" target=\"_blank\"><img src=\"Images/ouc.png\" title=\"中国海洋大学\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeYNOU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.tust.edu.cn/index.html\" target=\"_blank\"><img src=\"Images/TUST.jpg\" title=\"天津科技大学\" height=\"120\"></a>");
document.write("</div>");
document.write("</div>");

